import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Mouse from "./components/Mouse";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "KK | Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} h-screen flex flex-col lg:flex-row`}
      >
        <Mouse />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
