import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Mouse from "./components/Mouse";
import { Providers } from "./providers";

const montserrat = Montserrat({ subsets: ["latin"] });

const isMobileDevice = () => {
  if (typeof window !== "undefined") {
    return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
      navigator.userAgent
    );
  }
  return false; // Fallback in case window or navigator is not available
};

export const metadata = {
  title: "KK | Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.className} h-screen flex flex-col lg:flex-row`}
      >
        <Providers>
          {!isMobileDevice() && <Mouse />}
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
